### ISSUE TITLE
Running steps of the scripts？

### ISSUE THREAD

**Issue by cpuxzb** [jaeho3690/LIDC-IDRI-Classification#1]
I wonder the order of the scripts when I run them.

**Comment by jaeho3690** [comment]
Hi, sorry, I didn't had the time to upload the Readme file :( 
1. Prepare dataset -> prepare_data.py
This will create an image file consisting of shape (224,224,3) which is the format needed for efficient net
2. Train_efficientnet.py
Run this script to train the efficient net

**Comment by cpuxzb** [comment]
thank you for your reply.I will try to run the script according to your reply.



> Hi, sorry, I didn't had the time to upload the Readme file :(
> 
> 1. Prepare dataset -> prepare_data.py
>    This will create an image file consisting of shape (224,224,3) which is the format needed for efficient net
> 2. Train_efficientnet.py
>    Run this script to train the efficient net
