### ISSUE TITLE
Directory

### ISSUE THREAD

**Issue by cpuxzb** [jaeho3690/LIDC-IDRI-Classification#2]
When I look in the  prepare_data.py in folder prepare_dataset,the directory confused me.The LIDC-IDRI  dataset is organized  like LIDC-IDRI/LIDC-IDRI-0001/....

**Comment by jaeho3690** [comment]
The lung cad system consists of multiple sequential stages. 
1. Segmenting the lung -> 2. Classifying the Lung.
This repository is for the second stage. You will have to go through the preprocesing step. I have also uploaded the repositories for the preprocessing step. 
check in this order

1. Lidc-idri processing
2. Lung Nodule segmentation
3. Lidc-idri classification

For this second, and their repository, I need some time to write the readme file.

**Comment by cpuxzb** [comment]
thank you for your reply.I will try to run the script according to your reply.

**Comment by jaeho3690** [comment]
Let me know if there is any trouble or questions.

**Comment by cpuxzb** [comment]
Ok，I will try later
